" ========================== Plugin
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'AndrewRadev/splitjoin.vim'
Plugin 'bronson/vim-visual-star-search'
Plugin 'brooth/far.vim'
Plugin 'dbakker/vim-projectroot'
Plugin 'dense-analysis/ale'
Plugin 'joshdick/onedark.vim'
Plugin 'kien/ctrlp.vim'
Plugin 'prettier/vim-prettier'
Plugin 'sheerun/vim-polyglot'
Plugin 'darthmall/vim-vue'
Plugin 'SirVer/ultisnips'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-surround'
"Plugin 'tpope/vim-obsession'
Plugin 'VundleVim/Vundle.vim'
call vundle#end()

" Netrw
let g:netrw_list_hide= '.*\.swp$,.*\.swo$'

" CtrlP
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 'ra'
let g:ctrlp_use_caching = 0
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\.git$\|\.yardoc\|node_modules\|log\|tmp$\|dist',
  \ 'file': '\.so$\|\.dat$|\.DS_Store$'
  \ }

" OneDark
let g:onedark_hide_endofbuffer=1
let g:onedark_termcolors=256

" UltiSnips
let g:UltiSnipsSnippetsDir="~/.vim"
let g:UltiSnipsSnippetDirectories=["myUltiSnippets"]
" populate arglist and clean all, for autocompletion for the snippets item name
au VimEnter * silent! argadd ~/.vim/myUltiSnippets/*.snippets | argdelete *

" ALE
let g:ale_sign_column_always = 1
let g:ale_linters_explicit = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_enter = 0
let g:ale_lint_on_save=1

let g:ale_linters = {
\   'javascript': ['eslint'],
\   'vue': ['eslint'],
\   'javascriptreact': ['eslint'],
\}
let g:ale_fixers = {
\   '*': ['eslint'],
\}

" Surround
let g:surround_{char2nr(">")} = "<\r>"

" ====================== BootStrap 
au BufNewFile,BufReadPost *.wxml set ft=wxml.html
au BufNewFile,BufReadPost *.wxss set ft=wxss.css
au BufNewFile,BufReadPost *.jsx set ft=javascript.javascriptreact
au BufEnter * silent! lcd %:p:h

filetype plugin indent on
syntax on
set autoindent
set autoread
set backspace=indent,eol,start
set visualbell
set cursorline
set complete+=k
set dictionary+=/usr/share/dict/words
set hidden
set hlsearch
set incsearch
set laststatus=2
set statusline=%F
set number
set ruler
set ignorecase
set smartcase
set tabstop=2 shiftwidth=2
set expandtab
set undodir=/tmp
set undofile
set wildmenu
set wildmode=list:longest,full
set path+=$PWD/**
set wildignore+=**/node_modules/** 
set includeexpr=substitute(v:fname,'^\\/','','')
set suffixesadd=.js,.jsx,.es,.es6,.cjs,.mjs,.jsm,.vue,.json
set termguicolors
colorscheme onedark

" =================== Keys Mapping

noremap <Space>f :Prettier<CR>
noremap <Space>l :ALEFix<CR>
noremap <Space>! :AsyncRun 
" Emmet like: div => <div><div>

noremap <Space>. :e $MYVIMRC<CR>
noremap <Space>so :so $MYVIMRC<CR>

noremap <Space>e :e .<CR>
noremap <Space>E :e <C-R>=projectroot#guess().'/'<CR><CR>

" Copy current file path
noremap <Space>cp :let @+ = expand("%:p")<CR>

noremap <Space>y "+y
noremap <Space>Y "+Y


inoremap <S-Tab> <Esc>yiWi<<Esc>Emma></<C-r>"><Esc>`ma
nnoremap S :w<CR>
nnoremap Q :q<CR>

noremap L :tabnext<CR>
noremap H :tabprevious<CR>
noremap <C-n> :tabnew<Cr>

map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

cnoremap :: <C-R>=projectroot#guess().'/'<CR>
